aws:
  kinesis:
    region_name: ${REGION_NAME:ap-northeast-1}
    stream_name: ${STREAM_NAME:sandbox}
    initial_position: ${INITIAL_POSITION:TRIM_HORIZON}
    timestamp: ${TIMESTAMP:20210101000000}
logging:
  level:
    root: ${LOG_LEVEL:INFO}