/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.junoha.sample.kinesis.consumer;

import org.junit.Test;
import static org.junit.Assert.*;

public class KinesisConsumerServiceTest {
    @Test public void testAppHasAGreeting() {
        KinesisConsumerService classUnderTest = new KinesisConsumerService('foo', 'ap-northeast-1');
        assertNotNull("Hello", "Nasty" );
    }
}
