aws:
  kinesis:
    region_name: ${REGION_NAME:ap-northeast-1}
    stream_name: ${STREAM_NAME:sandbox}
    seconds_to_run: ${SECONDS_TO_RUN:30}
    records_per_second: ${RECORDS_PER_SECOND:2000}
logging:
  level:
    root: ${LOG_LEVEL:INFO}