/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.junoha.sample.kinesis.producer;

import org.junit.Test;
import static org.junit.Assert.*;

public class KinesisProducerServiceTest {
    @Test public void testAppHasAGreeting() {
        KinesisProducerService kpsTest = new KinesisProducerService();
        assertNotNull("Hello", "Nasty" );
    }
}
